name: ✨ Feature
description: Template pour créer un issue "feature".
title: "[FEATURE] "
labels: ["feature"]

body:
  - type: input
    id: short_description
    attributes:
      label: Brève description
      description: Description du feature. Il peut-être pertinent d'inclure sa raison d'être, un user story et/ou les métriques de succès.
    validations:
      required: true