name: ✨ Feature
description: Template pour créer un issue "feature".
title: "[FEAT] "
labels: ["feature"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description du feature
      placeholder: |
         Décrivez le feature. Il peut-être pertinent d'inclure sa raison d'être, un user story et/ou les métriques de succès.
    validations:
      required: true