name: 🦠 Bug
description: Template pour créer un issue "bug".
title: "[BUG] "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Quel est le bug ?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire le problème ?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
    validations:
      required: true